name: auth service CI

on:
  push:
    branches:
      - "main"
    paths:
      - "authservice/**"

jobs:
  auth:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start the Build and Deploy Process
        run: echo "Start the Build and Deploy Process..."
      - name: Install and Setup JDK 11
        run: echo "Install and Setup JDK 11..."
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        run: echo "Build with Gradle..."
      - name: Build with Gradle
        working-directory: ./authservice
        run: ./gradlew build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          SERVICE_NAME: intellivest-auth-service
          ECR_REPO: ${YOUR_ECR_REPO}
          IMAGE_TAG: main
        working-directory: ./authservice
        run: |
          echo "Build, tag, and push image to Amazon ECR..."
          docker build -t ${{env.ECR_REPO}}/${{env.SERVICE_NAME}}:${{env.IMAGE_TAG}} .
          docker push ${{env.ECR_REPO}}/${{env.SERVICE_NAME}}:${{env.IMAGE_TAG}}
      - name: Job Completed Succesfully
        run: echo "Job Complete"